# Generated by Django 4.0.5 on 2022-09-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_email_message_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recpient',
            new_name='recipient',
        ),
    ]
